export const LETTER_REVEAL_BASE_DELAY_MS = 16;
export const LETTER_REVEAL_INITIAL_DELAY_MS = 100;
export const LETTER_REVEAL_LINE_BREAK_DELAY_MS = 120;
export const LETTER_REVEAL_PUNCTUATION_DELAY_MS = 72;
